return {
  'nvim-tree/nvim-web-devicons',
  lazy = true,
  config = function()
    require('nvim-web-devicons').set_default_icon('◎', '#6d8086', 65)
    require('nvim-web-devicons').set_icon({
      astro = {
        icon = '',
        color = '#FD971F',
        cterm_color = '208',
        name = 'Astro',
      },
      org = {
        icon = '',
        color = '#75A899',
        name = 'Org',
      },
      css = {
        icon = '',
        color = '#42a5f5',
        cterm_color = '75',
        name = 'Css',
      },
      dart = {
        icon = '',
        color = '#51a0cf',
        cterm_color = '25',
        name = 'Dart',
      },
      -- deb = {
      --   icon = '',
      --   name = 'deb',
      -- },
      Dockerfile = {
        icon = '',
        color = '#458ee6',
        cterm_color = '68',
        name = 'Dockerfile',
      },
      html = {
        icon = '',
        color = '#e44d26',
        cterm_color = '196',
        name = 'Html',
      },
      js = {
        icon = '󰌞',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Js',
      },
      json = {
        icon = '󰘦',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Json',
      },
      json5 = {
        icon = '󰘦',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Json5',
      },
      jsonc = {
        icon = '󰘦',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Jsonc',
      },
      kt = {
        icon = '󱈙',
        color = '#7F52FF',
        cterm_color = '99',
        name = 'Kotlin',
      },
      lock = {
        icon = '󰌾',
        color = '#bbbbbb',
        cterm_color = '250',
        name = 'Lock',
      },
      mp3 = {
        icon = '󰎆',
        color = '#E8274B',
        cterm_color = '45',
        name = 'Mp3',
      },
      -- mp4 = {
      --   icon = '',
      --   name = 'mp4',
      -- },
      out = {
        icon = '',
        name = 'out',
      },
      ['robots.txt'] = {
        icon = '󰚩',
        color = '#6d8086',
        cterm_color = '66',
        name = 'Robots',
      },
      toml = {
        icon = '',
        color = '#51a0cf',
        cterm_color = '74',
        name = 'Toml',
      },
      ts = {
        icon = '󰛦',
        color = '#519aba',
        cterm_color = '74',
        name = 'Ts',
      },
      -- rb = {
      --   icon = '',
      --   color = '#701516',
      --   cterm_color = '52',
      --   name = 'Rb',
      -- },
      -- rpm = {
      --   icon = '',
      --   name = 'rpm',
      -- },
      vue = {
        icon = '󰡄',
        color = '#8dc149',
        cterm_color = '113',
        name = 'Vue',
      },
      xz = {
        icon = '',
        color = '#6d8086',
        cterm_color = '66',
        name = 'Xz',
      },
      zip = {
        icon = '',
        color = '#6d8086',
        cterm_color = '66',
        name = 'Zip',
      },
      zsh = {
        icon = '',
        color = '#e37933',
        cterm_color = '172',
        name = 'Zsh',
      },
      bash = {
        icon = '',
        color = '#e37933',
        cterm_color = '172',
        name = 'Bash',
      },
      sh = {
        icon = '',
        color = '#e37933',
        cterm_color = '172',
        name = 'Sh',
      },
      ['.bashrc'] = {
        icon = '',
        color = '#e37933',
        cterm_color = '172',
        name = 'Bash',
      },

      -- Config files
      ['.prettierignore'] = {
        icon = '',
        color = '#41535b',
        cterm_color = '239',
        name = 'Prettierrc',
      },
      ['.prettierrc'] = {
        icon = '',
        color = '#41535b',
        cterm_color = '239',
        name = 'Prettierrc',
      },
      ['.prettierrc.json'] = {
        icon = '',
        color = '#41535b',
        cterm_color = '239',
        name = 'Prettierrc',
      },
      ['.prettierrc.js'] = {
        icon = '',
        color = '#41535b',
        cterm_color = '239',
        name = 'Prettierrc',
      },
      ['prettier.config.js'] = {
        icon = '',
        color = '#41535b',
        cterm_color = '239',
        name = 'Prettierrc',
      },
      -- ['.prettier.yaml'] = {
      --   icon = '',
      --   color = '#41535b',
      --   cterm_color = '239',
      --   name = 'Prettierrc',
      -- },
      ['yarn-error.log'] = {
        icon = '',
        color = '#458ee6',
        cterm_color = '68',
        name = 'Yarnerrorlog',
      },
      ['yarn.lock'] = {
        icon = '',
        color = '#458ee6',
        cterm_color = '68',
        name = 'Yarnlock',
      },
      ['.yarnrc'] = {
        icon = '',
        -- icon = '',
        color = '#458ee6',
        cterm_color = '68',
        name = 'Yarnconfig',
      },
      ['pnpm-lock.yaml'] = {
        icon = '',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Pnpmlock',
      },
      ['package.json'] = {
        icon = '',
        color = '#019833',
        cterm_color = '28',
        name = 'Npm_packagejson',
      },
      ['package-lock.json'] = {
        icon = '',
        color = '#019833',
        cterm_color = '28',
        name = 'Npm_packagejson',
      },
      ['.nvmrc'] = {
        icon = '',
        color = '#019833',
        cterm_color = '28',
        name = 'Npm_packagejson',
      },
      ['.eslintrc.js'] = {
        icon = '',
        color = '#4b32c3',
        cterm_color = '56',
        name = 'Eslintrc',
      },
      ['.eslintrc.json'] = {
        icon = '',
        color = '#4b32c3',
        cterm_color = '56',
        name = 'Eslintrc',
      },
      ['.babelrc'] = {
        icon = '',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Babelrc',
      },
      ['babel.config.js'] = {
        icon = '',
        color = '#F1F134',
        cterm_color = '185',
        name = 'Babelrc',
      },
      ['vite.config.js'] = {
        icon = '',
        color = '#FD971F',
        cterm_color = '208',
        name = 'viteconfigjs',
      },
      ['vite.config.ts'] = {
        icon = '',
        color = '#FD971F',
        cterm_color = '208',
        name = 'viteconfigts',
      },
      ['git'] = {
        icon = '',
        color = '#F14C28',
        cterm_color = '196',
        name = 'GitLogo',
      },
      ['.gitattributes'] = {
        icon = '',
        color = '#F14C28',
        cterm_color = '196',
        name = 'GitLogo',
      },
      ['.gitconfig'] = {
        icon = '',
        color = '#F14C28',
        cterm_color = '196',
        name = 'GitLogo',
      },
      ['.gitignore'] = {
        icon = '',
        color = '#F14C28',
        cterm_color = '196',
        name = 'GitLogo',
      },
      NeogitStatus = {
        icon = '',
        color = '#F14C28',
        name = 'GitBranchStatus',
      },
      DiffviewFiles = {
        icon = '',
        color = '#F14C28',
        name = 'GitBranchStatus',
      },

      -- Media
      avif = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Avif',
      },
      bmp = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Bmp',
      },
      gif = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Gif',
      },
      ico = {
        icon = '󰈟',
        color = '#cbcb41',
        cterm_color = '185',
        name = 'Ico',
      },
      jpeg = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Jpeg',
      },
      jpg = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Jpg',
      },
      jxl = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'JpegXl',
      },
      png = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Jpg',
      },
      webp = {
        icon = '󰈟',
        color = '#89e051',
        cterm_color = '113',
        name = 'Webp',
      },
    })
  end,
}
