-- require('shade').setup({
--   overlay_opacity = 50,
--   opacity_step = 1,
--   keys = {
--     brightness_up = '<M-Up>',
--     brightness_down = '<M-Down>',
--     toggle = '<Leader>S',
--   },
-- })
