#!/bin/bash
set -e
tmpfile=$1

files=$(
	readarray -t ARRAY <"$tmpfile"
	# IFS=' '
	echo "${ARRAY[*]}"
)

files=${files//\"/}
rm "$tmpfile"

result=$(curl -F"file=@$files" -Fexpires=72 https://0x0.st)

echo " "
echo "${result}" | clip
echo "${result}"
