return {
  window = {
    position = 'float',
    mappings = {
      ['A'] = 'git_add_all',
      ['gu'] = 'git_unstage_file',
      ['ga'] = 'git_add_file',
      ['gr'] = 'git_revert_file',
      ['gc'] = 'git_commit',
      ['gp'] = 'git_push',
      ['gg'] = 'git_commit_and_push',
      -- ['o'] = { 'show_help', nowait = false, config = { title = 'Order by', prefix_key = 'o' } },
      -- ['oc'] = { 'order_by_created', nowait = false },
      -- ['od'] = { 'order_by_diagnostics', nowait = false },
      -- ['om'] = { 'order_by_modified', nowait = false },
      -- ['on'] = { 'order_by_name', nowait = false },
      -- ['os'] = { 'order_by_size', nowait = false },
      -- ['ot'] = { 'order_by_type', nowait = false },
      ['oc'] = 'none',
      ['od'] = 'none',
      ['om'] = 'none',
      ['on'] = 'none',
      ['os'] = 'none',
      ['ot'] = 'none',
    },
  },
}
