reporting: 'on'
startuppopupversion: 1
gui:
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - "#546178"
    optionsTextColor:
      - "#546178"
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
keybinding:
  universal:
    # quit: '<esc>'
    # quit-alt1: '<c-c>' # alternative/alias of quit
    # return: 'q' # return to previous menu, will quit if there's nowhere to return
    remove: 'x'
    optionMenu: 'm' # show help menu
    createRebaseOptionsMenu: 'X'
    scrollUpMain-alt1: '{' # main panel scrool up
    scrollDownMain-alt1: '}' # main panel scrool down
    nextScreenMode: 'O'
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
customCommands:
  - key: 'e'
    command: 'nvim {{.SelectedFile.Name}}'
    description: 'open in neovim'
    context: 'files'
    subprocess: true
