reporting: 'on'
startuppopupversion: 1
gui:
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - "#546178"
    optionsTextColor:
      - "#546178"
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
keybinding:
  universal:
    # quit: '<esc>'
    # quit-alt1: '<c-c>' # alternative/alias of quit
    # return: 'q' # return to previous menu, will quit if there's nowhere to return
    remove: 'x'
    optionMenu: 'm' # show help menu
    createRebaseOptionsMenu: 'X'
    scrollUpMain-alt1: '{' # main panel scrool up
    scrollDownMain-alt1: '}' # main panel scrool down
    nextScreenMode: 'O'
    filteringMenu: '<c-f>'
  commits:
    renameCommit: 'R'
    renameCommitWithEditor: '<f2>'
  files:
    viewResetOptions: 'X' # -- has conflict

notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
customCommands:
  - key: 'd'
    command: 'git diff {{.SelectedFile.Name}}'
    description: 'Open diff'
    context: 'global' # add all context
    subprocess: true
  - key: 'G'
    command: 'git reset --soft HEAD^'
    description: 'Undo last commit'
    context: 'commits' # add all context

os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
  # openCommand: 'start "" {{filename}}'

git:
  paging:
    colorArg: always
    pager: delta --side-by-side --paging=never
