# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#defaulthttps://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
reporting: 'on'
startuppopupversion: 1
gui:
  nerdFontsVersion: 3
  border: 'rounded'
  authorColors:
    # 'John Smith': 'red'
    '*': 'yellow'
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - '#546178'
    optionsTextColor:
      - '#546178'
    selectedLineBgColor:
      - '#363C51'
    selectedRangeBgColor:
      - reverse
keybinding:
  universal:
    optionMenu: 'm' # show help menu
    createRebaseOptionsMenu: 'K'
    remove: 'x'
    scrollUpMain-alt1: 'u'
    scrollDownMain-alt1: 'd'
    nextScreenMode: "'"
    prevScreenMode: '"'
    filteringMenu: '<c-f>'
    gotoTop: 'g'
    gotoBottom: 'G'
  commits:
    renameCommit: 'R'
    renameCommitWithEditor: '<f2>'
    viewResetOptions: 'X'
  files:
    viewResetOptions: 'X' # -- has conflict
  stash:
    popStash: 'K'

notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
customCommands:
  - key: 'D'
    command: 'git diff {{.SelectedFile.Name}}'
    description: 'Open diff'
    context: 'global' # add all context
    subprocess: true
  - key: 'U'
    command: 'git reset --soft HEAD^'
    description: 'Undo last commit'
    context: 'commits' # add all context

os:
  editPreset: 'nvim' # https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#configuring-file-editing

git:
  paging:
    colorArg: always
    pager: delta --side-by-side --paging=never
