# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
use = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = false, bg = "#3E425D" }
preview_hovered = { underline = true }

# Find & Search count
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "#282c34", bg = "magenta", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen", bg = "lightgreen" }
marker_cut      = { fg = "lightred", bg = "lightred" }
marker_marked   = { fg = "magenta", bg = "magenta" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active   = { bg = "#4C5272", fg = "#abb2bf" }
tab_inactive = { bg = "#2D3343", fg = "#abb2bf" }
tab_width    = 20

# Count
count_copied   = { fg = "#282c34", bg = "green" }
count_cut      = { fg = "#282c34", bg = "red" }
count_selected = { fg = "#282c34", bg = "yellow" }

# Border
border_symbol = "│"
border_style  = { fg = "darkgray" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
overall = { fg = "#8b95a7", bg = "#2D3343" }
# sep_left = { open = "", close = "" }
# sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#8b95a7", bg = "#3E425D" }
progress_normal = { fg = "#3E425D" }
progress_error  = { fg = "red" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }

[mode]
normal_main = { bg = "blue", fg = "#282c34", bold = true }
normal_alt  = { bg = "#3E425D", fg = "#abb2bf", bold = true }
select_main = { bg = "magenta", fg = "#282c34", bold = true }
select_alt  = { bg = "#3E425D", fg = "magenta", bold = true }
unset_main  = { bg = "red", fg = "#282c34", bold = true }
unset_alt   = { bg = "#3E425D", fg = "red", bold = true }
# : }}}


# : Select {{{

[select]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#2d3343" }
cand            = { fg = "lightmagenta" }
rest            = { fg = "darkgray" }
desc            = { fg = "#a5b0c5" }
separator       = " ➜ "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "magenta" }
run     = { fg = "cyan" }
desc    = {}
hovered = { reversed = false, bg = "#3E425D" }
footer  = { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}

